---
title: "Data_Science_Challenge_EDA"
author: "Aldwin Arambulo"
date: "2024-07-22"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, Warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(dplyr)
library(readr)
library(rmarkdown)

```


# EDA

## Life expectancy data

```{r}
# Loading the data
le_df <- read_csv("data/life-expectancy.csv")
paged_table(le_df)
```

```{r}
# Checking the dimensions of the data
dim(le_df)
```

```{r}
# Checking the structure of the data
str(le_df)
```

```{r}
# Checking the summary of the data
summary(le_df)
hist(le_df$Year)
```

```{r}
# Remove rows with missing values
missing_vals_le_df <- le_df %>% drop_na()
dim(missing_vals_le_df)
```

```{r}
# Checking for entities with missing Code values
missing_entity_codes <- le_df %>% filter(is.na(Code)) %>% 
  select(Entity) %>% distinct()
missing_entity_codes
```



```{r}
# create a world heatmap with the life expectancy of each country
colnames(le_df)[4] <- "Life_Expectancy"
le_df$Entity[le_df$Entity == "United States"] <- "USA"
le_df$Entity[le_df$Entity == "Democratic Republic of Congo"] <- "Democratic Republic of the Congo"
le_df$Entity[le_df$Entity == "Congo"] <- "Republic of Congo"
life_expectancy_2020 = subset(le_df, Year=='2020')

library(tidyverse)
library(magick)

world_map = subset(map_data("world"), region != "Antarctica")
ggplot() +
  geom_polygon(data = world_map, aes(x = long, y = lat, group = group),
               fill = "grey", alpha = 0.3) +
  geom_map(map = world_map, data = life_expectancy_2020, aes(map_id=Entity, fill=Life_Expectancy)) +
  scale_fill_gradient(low = "#cc4c02", high = "#fff7bc", name = "Life Expectancy") + theme_void() + coord_fixed(1.2)
```

## Polio vaccination data

```{r}
# Loading the data
polio_df <- read_csv("data/number-of-estimated-paralytic-polio-cases-by-world-region.csv")
paged_table(polio_df)
```


```{r}
# Line graph of the number of estimated paralytic polio cases
estimated_polio_cases <- polio_df %>% 
  filter(Entity == "World") %>% 
  ggplot(aes(x = Year, y = `Estimated polio cases`)) +
  geom_line() +
  labs(title = "Number of estimated paralytic polio cases by year",
       x = "Year",
       y = "Number of estimated paralytic polio cases")

estimated_polio_cases
```





# Notes

- There is an entity `World` which I'm guessing is the overall population
- There are multiple entities with missing `Code` values as seen above

We need to decide what time period we should focus on.  Some countries have stats earlier than 1950.  Most countries start from 1950 so I reckon we can focus on that time period onwards.